version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '18080:8080'
    volumes:
      - ./trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
