version: '3.9'
services:
  headscale:
    container_name: headscale
    volumes:
        - ./config:/etc/headscale/
        - ./keys:/var/lib/headscale/
    image: headscale/headscale:latest
    command: headscale serve
    restart: unless-stopped
    ports:
        - 8082:8080
        - 9091:9090

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    container_name: headscale-ui
    restart: unless-stopped
    ports:
      - 8443:443
