version: '3.9'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-on9isation
    restart: always
    command: tunnel --no-autoupdate run --token ${ON9ISATION_TOKEN}

