version: '3.9'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-itcatgor
    restart: always
    command: tunnel --no-autoupdate run --token ${ITCATGOR_TOKEN}

