- name: password change
  hosts: localhost
  connection: local
  vars_files:
    - "../vault.yml"
  become: true
  vars_prompt:
  - name: new_password
    prompt: "Enter new password"
  tasks:
  - name: change user's password
    user:
      name: "{{ ansible_user }}"
      state: present
      password: "{{ new_password|password_hash('sha512') }}"
