---
- name: Remove Docker and Docker Compose
  hosts: jarvis
  become: true
  tasks:
    - name: Stop docker server
      ignore_errors: yes
      service:
        name: docker
        state: stopped

    - name: Remove Docker Compose binary
      file:
        path: /usr/local/bin/docker-compose
        state: absent

    - name: Uninstall Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent

    - name: Remove Docker APT repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: absent
