- name: Install Docker and Docker Compose
  hosts: all
  become: yes

  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: "yes"

    - name: apt
      apt:
        update_cache: yes
        upgrade: "dist"

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    - name: test docker
      command: docker info
      become: true
