version: '3.9'
services:
    minio:
        container_name: minio
        image: quay.io/minio/minio
        environment:
            - MINIO_ROOT_PASSWORD=P@ssw0rd
            - MINIO_ROOT_USER=admin
        volumes:
            - './data:/data'
        ports:
            - '9090:9090'
            - '9000:9000'
        command: 'server /data --console-address ":9090"'
