appConfig:
  theme: one-dark
  layout: auto
  iconSize: medium
  language: en
  webSearch:
    searchEngine: google
  statusCheck: true
  statusCheckInterval: 60
  customCss: |+

pageInfo:
  title: HomeLAB Dashboard
  description: Welcome to HomeLAB Dashboard
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Docs
      path: https://dashy.to/docs
  footerText: Designed by Technicat
sections:
  - name: Today
    icon: far fa-smile-beam
    displayData:
      collapsed: false
      hideForGuests: false
      cols: 1
    widgets:
      - type: clock
        options:
          timeZone: Asia/Hong_Kong
          format: en-GB
        id: 0_513_clock
      - type: weather
        options:
          apiKey: efdbade728b37086877a5e83442004db
          city: hongkong
        id: 1_513_weather
  - name: Productivity
    displayData:
      collapsed: false
      cols: 3
    items:
      - title: Proxmox Main
        description: My Proxmox
        icon: hl-proxmox
        url: https://pve.local.itcatgor.com
        target: newtab
        statusCheck: false
        id: 0_1302_proxmoxmain
      - title: Proxmox mini
        description: Proxmox2
        icon: hl-proxmox
        url: https://pve2.local.itcatgor.com
        target: newtab
        statusCheck: false
        id: 1_1302_proxmoxmini
      - title: Trilium
        description: Self-hosted Note
        icon: hl-trilium
        url: https://notes.on9isation.xyz
        target: newtab
        statusCheck: true
        id: 2_1302_trilium
      - title: Synology
        description: Synology
        icon: hl-synology
        url: https://nas.local.itcatgor.com
        target: newtab
        statusCheck: true
        id: 3_1302_synology
      - title: pfsense
        description: Firewall Central Management
        icon: hl-pfsense
        url: https://10.8.8.8:8888
        target: newtab
        statusCheckAllowInsecure: true
        id: 4_1302_pfsense
      - title: Pi-Hole
        description: DNS settings for ad & tracker blocking
        icon: hl-pihole
        url: https://pihole.local.itcatgor.com/admin
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 5_1302_pihole
      - title: Uptime-Kuma
        description: monitoring with ping
        icon: hl-uptime-kuma
        url: https://uptime.local.itcatgor.com
        target: newtab
        statusCheck: true
        id: 6_1302_uptimekuma
      - title: Grafana
        description: Data visualised on dashboards
        icon: hl-grafana
        url: https://grafana.local.itcatgor.com
        target: newtab
        id: 7_1302_grafana
      - title: Portainer
        description: Docker container management
        icon: hl-portainer
        url: https://portainer.local.itcatgor.com
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 8_1302_portainer
      - title: Nginx Reverse Proxy
        description: Nginx Reverse Proxy
        icon: hl-nginx
        url: https://nginx.local.itcatgor.com
        target: newtab
        statusCheck: true
        id: 9_1302_nginxreverseproxy
      - title: Dozzle
        description: Docker container web log viewer
        icon: hl-dozzle
        url: http://dozzle.local.itcatgor.com
        target: newtab
        statusCheck: true
        id: 10_1302_dozzle
  - name: VM CPU Usage
    icon: fas fa-microchip
    displayData:
      rows: 2
    widgets:
      - type: iframe
        useProxy: true
        options:
          url: >-
            https://grafana.local.itcatgor.com/d-solo/Dp7Cd57Zza/proxmox-via-prometheus?orgId=1&refresh=5m&panelId=2
          frameHeight: 500
        id: 0_960_iframe
  - name: VM Memory Usage
    icon: fas fa-tachometer
    widgets:
      - type: iframe
        useProxy: true
        options:
          url: >-
            https://grafana.local.itcatgor.com/d-solo/Dp7Cd57Zza/proxmox-via-prometheus?orgId=1&refresh=5m&panelId=5
          frameHeight: 500
        id: 0_1361_iframe
  - name: Container Memort Usage
    icon: fas fa-tachometer
    widgets:
      - type: iframe
        useProxy: true
        options:
          url: >-
            https://grafana.local.itcatgor.com/d-solo/htoVWdxGt/docker-cadvisor?orgId=1&refresh=5m&panelId=16
          frameHeight: 500
        id: 0_2124_iframe
