version: "3.5"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: Dashy
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
    ports:
      - 4000:8080
    dns:
      - 10.0.50.53
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
