version: '3.3'
services:
  gotify:
    image: gotify/server
    container_name: gotify
    ports:
      - 82:80
    volumes:
      - ./gotify:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Asia/Hong_Kong

