version: '3.7'
services:

  prometheus:
    image: prom/prometheus:v2.40.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  # links:
  #   - alertmanager:alertmanager
    networks:
      - monitor
    restart: always

  #alertmanager:
  # image: prom/alertmanager
  # ports:
  #   - 9093:9093
  # volumes:
  #   - ./alertmanager/:/etc/alertmanager/
  # networks:
  #   - monitor
  # restart: always
  # command:
  #   - '--config.file=/etc/alertmanager/config.yml'
  #   - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

    env_file:
      - ./grafana/config.env
    networks:
      - monitor
    restart: always

volumes:
  prometheus_data:
    driver_opts:
      type: nfs
      o: addr=192.168.50.50,nfsvers=4 #using nfs
      device: :/volume1/docker/prometheus-grafana/prometheus
  grafana_data:
    driver_opts:
      type: nfs
      o: addr=192.168.50.50,nfsvers=4 #using nfs
      device: :/volume1/docker/prometheus-grafana/grafana
networks:
  monitor:
